### ISSUE TITLE
Move founds before closing channel

### ISSUE THREAD

**Issue by Falsen** [lightningnetwork/lightning-rfc#610] opened 2019-05-15 18:32 UTC
I just got one of my channels closed at 67000 satoshis. Wouldn't it be possible to first move funds to one of my open other open channels before closing this one? This would result in less UTXOs and I wouldn't have some unwanted on chain funds.

**Comment by t-bast** [comment] 2020-07-07 13:06
If your channel peer decides to close, you can't stop him.
And once the transaction is broadcast, if the peer doesn't cooperate, you have to wait for the funds to be available on-chain.
This is by design of the channel mechanism and we can't change that.

If you are the one closing the channel and your peer is online you can definitely move your funds before closing, and that's an implementation issue, not a spec one.

**Closed by t-bast** 2020-07-07 13:06 UTC
